# Generated by Django 3.0.5 on 2020-07-19 13:42

import datetime
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 7, 19, 13, 42, 43, 868933))),
            ],
        ),
    ]
