# Generated by Django 3.0.5 on 2020-07-19 13:43

import datetime
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 7, 19, 13, 43, 8, 391899))),
            ],
        ),
    ]
