# Generated by Django 3.0.5 on 2020-07-19 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 13, 46, 14, 451297)),
        ),
    ]
